CLASSES = [
    "Frijol",
    "Calabaza Amarga",
    "Calabaza de Botella",
    "Berenjena",
    "Brócoli",
    "Repollo",
    "Pimiento",
    "Zanahoria",
    "Coliflor",
    "Pepino",
    "Papaya",
    "Papa",
    "Calabaza",
    "Rábano",
    "Tomate",
]
